// ============================================================
// STATIC SITE DATA
// Update this file with real RTIFN Osun leadership details
// ============================================================

export const SITE = {
  name: 'RTIFN Osun State Chapter',
  tagline: 'Relax, Tinubu Is Fixing Nigeria',
  description: 'Official platform of RTIFN Osun State Chapter — communicating President Bola Ahmed Tinubu\'s reform agenda to the people of Osun State.',
  email: 'info@rtifnosun.org',
  phone: '+234 800 000 0000',
  whatsapp: 'https://wa.me/2348000000000',
  address: 'RTIFN Secretariat, Osogbo, Osun State, Nigeria',
  social: {
    facebook: 'https://facebook.com/RTIFNOsun',
    twitter: 'https://twitter.com/RTIFNOsun',
    instagram: 'https://instagram.com/RTIFNOsun',
    youtube: 'https://youtube.com/@RTIFNOsun',
    telegram: 'https://t.me/RTIFNOsun',
  }
}

export const EXECUTIVES = [
  {
    id: 1,
    name: 'Hon. [State Coordinator Name]',
    position: 'State Coordinator',
    bio: 'Leads the overall strategic direction of RTIFN Osun State Chapter, coordinating activities across all 30 local government areas and representing the chapter at the national level.',
    photo: null,
    initials: 'SC',
  },
  {
    id: 2,
    name: 'Hon. [Deputy Coordinator Name]',
    position: 'Deputy State Coordinator',
    bio: 'Assists the State Coordinator in day-to-day administration and leads key mobilization initiatives across Osun State\'s senatorial districts.',
    photo: null,
    initials: 'DC',
  },
  {
    id: 3,
    name: 'Barr. [Secretary Name]',
    position: 'State Secretary',
    bio: 'Manages all official documentation, correspondence, and administrative records of RTIFN Osun State Chapter.',
    photo: null,
    initials: 'SS',
  },
  {
    id: 4,
    name: 'Mr. [Media Director Name]',
    position: 'Media Director',
    bio: 'Oversees all media relations, digital communications, and public information campaigns for RTIFN Osun State Chapter.',
    photo: null,
    initials: 'MD',
  },
  {
    id: 5,
    name: 'Dr. [Comms Head Name]',
    position: 'Strategic Communications Head',
    bio: 'Develops and executes communication strategies to effectively convey President Tinubu\'s reform agenda to the citizens of Osun State.',
    photo: null,
    initials: 'CH',
  },
  {
    id: 6,
    name: 'Comrade [Mobilization Director Name]',
    position: 'Mobilization Director',
    bio: 'Coordinates grassroots mobilization efforts, managing ward-level campaigns and recruiting new members across all 30 LGAs of Osun State.',
    photo: null,
    initials: 'MB',
  },
]

export const ACHIEVEMENTS = [
  {
    id: 1,
    slug: 'fuel-subsidy-reform',
    icon: '⛽',
    title: 'Fuel Subsidy Reform',
    summary: 'The bold removal of fuel subsidies freed over ₦11 trillion annually for reinvestment in critical infrastructure and welfare programs.',
    detail: 'On May 29, 2023, President Tinubu made the historic declaration removing the fuel subsidy that had drained Nigeria\'s resources for decades. This freed up over ₦11 trillion annually — money that is now being redirected to education, healthcare, infrastructure, and direct welfare support for Nigerians.',
    category: 'Fiscal Reform',
    color: 'from-green-700 to-green-500',
  },
  {
    id: 2,
    slug: 'forex-unification',
    icon: '💱',
    title: 'Forex Unification & Reserve Growth',
    summary: 'Unification of the foreign exchange market has attracted investment and improved transparency in Nigeria\'s financial system.',
    detail: 'The unification of Nigeria\'s multiple exchange rates into a single market-driven rate has increased investor confidence, attracted diaspora remittances, and improved the transparency of Nigeria\'s financial system.',
    category: 'Finance',
    color: 'from-green-800 to-green-600',
  },
  {
    id: 3,
    slug: 'cashless-government',
    icon: '💳',
    title: 'Cashless Government Operations',
    summary: 'Digitization of government payments has eliminated ghost workers, reduced leakages, and brought unprecedented transparency to public finance.',
    detail: 'The aggressive push toward digital government payments has dramatically reduced the opportunities for financial leakages, eliminated thousands of ghost workers from payroll systems, and brought greater accountability to how public funds are managed.',
    category: 'Digital Governance',
    color: 'from-green-700 to-emerald-500',
  },
  {
    id: 4,
    slug: 'faac-allocation',
    icon: '📈',
    title: 'Increased FAAC Allocation',
    summary: 'Monthly federation account distributions to states have surged, giving Osun and other states significantly more development resources.',
    detail: 'As a direct result of the subsidy removal and improved revenue collection, monthly FAAC allocations to states and LGAs have grown substantially. Osun State now receives more resources for local development than under any previous administration.',
    category: 'Federalism',
    color: 'from-emerald-700 to-green-500',
  },
  {
    id: 5,
    slug: 'minimum-wage-workers',
    icon: '👷',
    title: 'Workers Welfare Reforms',
    summary: 'New minimum wage negotiations and welfare policies demonstrate Tinubu\'s commitment to improving the lives of Nigerian workers.',
    detail: 'The Tinubu administration has pushed through significant improvements in workers\' welfare, including new minimum wage negotiations, improved civil service conditions, and targeted support programs for vulnerable Nigerian workers.',
    category: 'Labour Policy',
    color: 'from-green-600 to-teal-500',
  },
  {
    id: 6,
    slug: 'infrastructure-investment',
    icon: '🏗️',
    title: 'Infrastructure Investment',
    summary: 'Unprecedented investment in roads, bridges, rail, and power infrastructure is transforming Nigeria\'s economic landscape.',
    detail: 'The Tinubu administration has committed billions to repairing and expanding Nigeria\'s critical infrastructure. New road projects, rail expansions, and power sector investments are creating jobs and reducing the cost of business across the country.',
    category: 'Infrastructure',
    color: 'from-green-800 to-green-500',
  },
]

export const EVENTS = [
  {
    id: 1,
    title: 'RTIFN Osun State Executive Meeting',
    date: '2024-03-25',
    time: '10:00 AM',
    location: 'RTIFN Secretariat, Osogbo',
    type: 'meeting',
    status: 'upcoming',
    description: 'Monthly executive council meeting to review chapter activities, plan upcoming outreach, and coordinate with national leadership.',
  },
  {
    id: 2,
    title: 'Community Town Hall — Ife Central LGA',
    date: '2024-03-28',
    time: '2:00 PM',
    location: 'Ile-Ife Community Hall',
    type: 'outreach',
    status: 'upcoming',
    description: 'Public town hall explaining Tinubu\'s economic reforms in simple terms to citizens of Ife Central Local Government Area.',
  },
  {
    id: 3,
    title: 'RTIFN Media Briefing — Q1 2024',
    date: '2024-04-05',
    time: '11:00 AM',
    location: 'Osogbo Press Centre',
    type: 'media',
    status: 'upcoming',
    description: 'Quarterly press briefing to update media on RTIFN Osun activities and the latest achievements of the Tinubu administration.',
  },
  {
    id: 4,
    title: 'Ward-Level Sensitization — Isokan LGA',
    date: '2024-04-12',
    time: '9:00 AM',
    location: 'Isokan LGA, Multiple Wards',
    type: 'mobilization',
    status: 'upcoming',
    description: 'Intensive ward-level engagement campaign across all wards of Isokan LGA explaining government policies and recruiting new members.',
  },
  {
    id: 5,
    title: 'RTIFN Osun Inaugural Summit 2024',
    date: '2024-02-15',
    time: '9:00 AM',
    location: 'Olaiya, Osogbo',
    type: 'meeting',
    status: 'past',
    description: 'Historic inaugural summit of RTIFN Osun State Chapter bringing together representatives from all 30 LGAs.',
  },
  {
    id: 6,
    title: 'Community Outreach — Boripe LGA',
    date: '2024-02-22',
    time: '10:00 AM',
    location: 'Iragbiji, Boripe LGA',
    type: 'outreach',
    status: 'past',
    description: 'Successful community engagement in Boripe LGA with over 500 citizens participating.',
  },
]

export const BLOG_CATEGORIES = [
  'Tinubu Achievements',
  'Economic Reforms',
  'RTIFN Activities',
  'Policy Explainers',
  'Press Releases',
  'Grassroots Mobilization',
]

export const OSUN_LGAS = [
  'Atakumosa East', 'Atakumosa West', 'Ayedaade', 'Ayedire',
  'Boluwaduro', 'Boripe', 'Ede North', 'Ede South',
  'Egbedore', 'Ejigbo', 'Ife Central', 'Ife East',
  'Ife North', 'Ife South', 'Ifedayo', 'Ifelodun',
  'Ila', 'Ilesa East', 'Ilesa West', 'Irepodun',
  'Irewole', 'Isokan', 'Iwo', 'Obokun',
  'Odo-Otin', 'Ola-Oluwa', 'Olorunda', 'Oriade',
  'Orolu', 'Osogbo',
]
